import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Grid, Box, Flex } from "@chakra-ui/react";
import Navbar from "@/components/parts/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <main
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Box maxH={"dvh"} maxW="dvw" overflow={"hidden"}>{children}</Box>
          </main>
        </Provider>
      </body>
    </html>
  );
}
